config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :locations, only: [:show]

  get "/i18n" => 'application#i18n', as: :i18n
  root to: 'patients#index'

end

app/models/concerns/i18nable.rb
module Concerns
  module I18nable
    extend ActiveSupport::Concern
    included do 
      class << self 
        def avaliable_genders 
          I18n.t("field_genders")
        end

        def avaliable_statuses 
          I18n.t("field_statuses")
        end
      end
    end
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :name
  validates_length_of :name, maximum: 80
  validates_length_of :code, maximum: 10
  has_many :patients
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  include Concerns::I18nable
  MAX_ID_LENGTH = 6
  validates_presence_of :first_name, :last_name, :status_id, :location_id
  validates_inclusion_of :status_id, in: 0...avaliable_statuses.count
  validates_inclusion_of :gender_id, in: 0...avaliable_genders.count
  validates_length_of :first_name, maximum: 30
  validates_length_of :middle_name, maximum: 10
  validates_length_of :last_name, maximum: 30
  delegate :name, to: "location", prefix: 'location', allow_nil: true

  belongs_to :location
  scope :onTreatment, -> { where(status_id: 2) }
  scope :not_deleted, -> { where(deleted: false) }

  def full_name
    "#{self.first_name}, #{[self.last_name, self.middle_name].join(" ")}"
  end

  def age
    if self.birthday.present?
      Date.today.year - self.birthday.year
    end
  end

  def mr_number 
    need_length = MAX_ID_LENGTH - self.id.to_s.length
    if need_length > 0
      "MR#{"0" * need_length}#{self.id}"
    else
      "MR#{self.id}"
    end
  end

  def gender 
    self.class.avaliable_genders[self.gender_id]
  end

  def status 
    self.class.avaliable_statuses[self.status_id]
  end

  def viewed_count_up
    self.update_attributes(viewed_count: self.viewed_count + 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def render_404
    render json: {status: 404}, status: 404
  end

  def i18n
    locales = ['zh-CN', 'en']
    if params[:locale].to_s.in?(locales)
      session[:locale] = params[:locale]
    end
    redirect_to :back
  end

  private
  def set_locale
    if session[:locale].present?
      I18n.locale = session[:locale]
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def show
    @location = Location.includes(:patients).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index 
    @patients = Patient.not_deleted
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def show
    @patient.viewed_count_up
  end

  def edit
  end

  def update
    if @patient.update_attributes(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient.update_attributes(deleted: true)
    redirect_to action: :index
  end

  private
  def patient_params 
    params.require(:patient).permit(:last_name, :first_name, :middle_name, :status_id, :gender_id, :location_id, :birthday)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  rescue ActiveRecord::RecordNotFound => _
    render_404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def genders_values
    Patient.avaliable_genders.each_with_index.map { |name, idx| [name, idx]}[1..-1]
  end

  def location_values
    Location.select([:id, :name]).map { |loc| [loc.name, loc.id] }
  end

  def statuses_values
    Patient.avaliable_statuses.each_with_index.map { |name, idx| [name, idx]}
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand"><%= t("site.name") %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role='button' aria-haspopup='true' aria-expanded='false'><%= t("lan.select") %><span class='caret'></span></a>
          <ul class="dropdown-menu">
            <li>
            <a href="<%= i18n_path(locale: "zh-CN") %>"><%= t("lan.zh") %></a>
            </li>
            <li>
            <a href="<%= i18n_path(locale: "en") %>"><%= t("lan.en") %></a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patients</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/locations/show.html.erb
<div>
  <%= @location.name %>
  <%= render 'patients/patients', patients: @location.patients %>
</div>

app/views/patients/_form.html.erb
<div>
  <%= simple_form_for(@patient) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :middle_name %>
    <%= f.input :last_name %>
    <%= f.input :birthday, start_year: Date.today.year - 90, end_year: Date.today.year %>
    <%= f.input :status_id, as: :select, collection: statuses_values %>
    <%= f.input :location_id, as: :select, collection: location_values %>
    <%= f.input :gender_id, as: :radio_buttons, collection: genders_values %>
    <%= f.button :submit %>
    <%= link_to t("index.page.back"), patients_path %>
  <% end %>
</div>

app/views/patients/_patients.html.erb
<div>
  <% if patients.any? %>
    <table class='table'>
      <tr>
        <th><%= t("activerecord.attributes.patient.mr_number") %></th>
        <th><%= t("activerecord.attributes.patient.full_name") %></th>
        <th><%= t("activerecord.attributes.patient.age") %></th>
        <th><%= t("activerecord.attributes.patient.gender_id") %></th>
        <th><%= t("activerecord.attributes.patient.status_id") %></th>
        <th><%= t("activerecord.attributes.patient.location_id") %></th>
        <th><%= t("activerecord.attributes.patient.viewed_count") %></th>
        <th><%= t("index.page.operate") %></th>
      </tr>
      <% patients.each do |patient| %>
        <tr>
          <td><%= link_to patient.mr_number, patient %></td>
          <td><%= patient.full_name %></td>
          <td><%= patient.age %></td>
          <td><%= patient.gender %></td>
          <td><%= patient.status %></td>
          <td><%= patient.location_name %></td>
          <td><%= patient.viewed_count %></td>
          <td>
            <%= link_to t("index.page.edit"), edit_patient_path(patient) %>
            <%= link_to t("index.page.destroy"), patient, method: :delete, data: { confirm: t("index.page.confirm") } %>
          </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <%= t("index.page.nothing_to_show") %>
  <% end %>
</div>

app/views/patients/edit.html.erb
<%= render 'form' %>

app/views/patients/index.html.erb
<%= render 'patients', patients: @patients %>
<%= link_to t("index.page.new_patient"), new_patient_path %>

app/views/patients/new.html.erb
<%= render 'form' %>

app/views/patients/show.html.erb
<div>
  <dl class="dl-horizontal">
    <dt>
      <%= t("activerecord.attributes.patient.mr_number") %>:
    </dt>
    <dd>
      <%= @patient.mr_number %>
    </dd>
    <dt>
      <%= t("activerecord.attributes.patient.full_name") %>:
    </dt>
    <dd>
      <%= @patient.full_name %>
    </dd>
    <dt>
      <%= t("activerecord.attributes.patient.birthday") %>:
    </dt>
    <dd>
      <%= @patient.birthday %>
    </dd>
    <dt>
      <%= t("activerecord.attributes.patient.status_id") %>:
    </dt>
    <dd>
      <%= @patient.status %>
    </dd>
    <dt>
      <%= t("activerecord.attributes.patient.location_id") %>:
    </dt>
    <dd>
      <%= @patient.location_name %>
    </dd>
    <dt>
      <%= t("activerecord.attributes.patient.gender_id") %>:
    </dt>
    <dd>
      <%= @patient.gender %>
    </dd>
    <dt></dt>
    <dd>
      <%= link_to t("index.page.patient_list"), patients_path %>
      <%= link_to t("index.page.edit"), edit_patient_path(@patient) %>
    </dd>
  </ul>
</div>